server:
  port: 8080

spring:
  application:
    name: demo-server-test
        datasource:
          url: jdbc:mysql://${TIDB_HOST}:${TIDB_PORT}/${TIDB_DB}?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: ${TIDB_USER}
          password: ${TIDB_PASS}
          driver-class-name: com.mysql.cj.jdbc.Driver
